### ISSUE TITLE
[Documentation/user guide] How to run the custom kube-scheduler with wasm extension

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/kube-scheduler-wasm-extension#62]
**What happened**:
Currently, there is no quick start guide to get started on kube-scheduler-was-extension. A quick start guide should help in following ways: 
- Easy to get a hands on experience around how wasm extension works.
- Easy for new developers to get onboarded to the project. 

**What you expected to happen**:
A quick start guide should exist. 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- kube-scheduler-wasm-extension version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sanposhiho** [comment]
/kind documentation
/remove-kind bug

Please go ahead.
But, note that we don't need a very detailed one for now and defer it later since the user interfaces (like config) are still undecided and actively changed. If we created now, it would be troublesome to change the doc every time we change something user-facing.

**Comment by codefromthecrypt** [comment]
let's wait until https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/67 before documenting, because even how things initialize are still stabilizing. Prior to this I would like to make an easier, even if not unit testable sample as well. This will occur in the next few days!

**Comment by codefromthecrypt** [comment]
things are stable enough to try to document, if you are up to it!

**Comment by sanposhiho** [comment]
/retitle [Documentation/user guide] How to run the custom kube-scheduler with wasm extension
/priority next-release

**Comment by duanmengkk** [comment]
Hello everyone in the community, we have recently encountered a problem in the production environment. The schedulers of multiple projects need to be merged together, and we do not want to combine the code of multiple schedulers and recompile. We are considering that the scheduler-wasm-extension might solve our problem. The issue now is that we don't know whether this feature can be used with clusters of Kubernetes of version 1.21, and we also don't know how to build our scheduling framework like scheduler-plugins (https://github.com/kubernetes-sigs/scheduler-plugins). Are there any relevant documents? @codefromthecrypt @sanposhiho

**Comment by sanposhiho** [comment]
@duanmengkk 

First of all, this project is still early stage. Trying it as an early adopter and providing feedback to us would be very welcome though, I'd say you should be careful to test things before rolling it out to production.
Secondly, v1.21 is very old, given this project depends on Kubernetes v1.27, I'm not sure everything works with v1.21 Kubernetes cluster. 

For the usage of this project, you can refer to [our examples](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/tree/main/examples) to get how to build your wasm binary. Also, you have to use the scheduler that has [our scheduler plugin](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/tree/main/scheduler/plugin) enabled, which can be started thru [this entry point](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/blob/main/scheduler/cmd/scheduler/main.go). Eventually, we'll provide the scheduler with our scheduler plugin from our registry so that you just need to build your wasm binary and can use it thru the scheduler run via our docker image.

**Comment by duanmengkk** [comment]
> Secondly, v1.21 is very old, given this project depends on Kubernetes v1.27, I'm not very sure everything works with v1.21 Kubernetes cluster.
Thank you for your reply，maybe we can give it a try. @yuleichun-striving @qiuming520
